#On se met en sudo
sudo: required

#On dit a travis qu on a besoin de dockerd
services:
  - docker

before_install:
  - docker build -t damsnda/docker-react -f Dockerfile.dev .

#-- --coverage just for exit on a le coverage
script:
  - docker run damsnda/docker-react npm run test -- --coverage
