#On se met en sudo
sudo: required

#On dit a travis qu on a besoin de dockerd
services:
  - docker

before_install:
  - docker build -t damsnda/docker-react -f Dockerfile.dev .

#-- --coverage just for exit on a le coverage  
script:
  - docker run -e CI=true damsnda/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: 'docker-react2'
  env: 'DockerReact2-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-850514798169'
  bucket_path: 'docker-react2'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY